spring:
  application:
    name: forex-service
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1

server:
  port: 8000

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka



