spring:
  application:
    name: currency-conversion-service
  sleuth:
    sampler:
      probability: 1

server:
  port: 8100

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
#forex-service.ribbon.listOfServers=localhost:8000,localhost:8001